export default [
  {
    title: "IBPS PO CRP PO/MT XVI Online Form 2026",
    shortTitle: "IBPS PO XVI 2026",
    organization: "Institute of Banking Personnel Selection",
    advNumber: "CRP PO/MT-XVI/2026",
    category: "banking", vacancies: 5208,
    startDate: "02/08/2026", lastDate: "28/08/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 20, ageMax: 30,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840 (JMGS-I starting)",
    state: "All India", isFeatured: true,
    posts: [["Probationary Officer / Management Trainee", 5208]],
    elig: "Bachelor's Degree from recognized university. Age 20-30 years. Computer literacy and local language proficiency required.",
    siteUrl: "https://ibps.in", applyUrl: "https://ibps.in/CRP-PO-MT-XVI"
  },
  {
    title: "SBI PO Probationary Officer 2026 Online Form",
    shortTitle: "SBI PO 2026",
    organization: "State Bank of India",
    advNumber: "CRPD/PO/2026/26",
    category: "banking", vacancies: 600,
    startDate: "03/08/2026", lastDate: "30/08/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 750/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840 (JMGS-I starting)",
    state: "All India", isFeatured: true,
    posts: [["Probationary Officer (General)", 400], ["Probationary Officer (OBC)", 108], ["Probationary Officer (SC)", 60], ["Probationary Officer (ST)", 32]],
    elig: "Graduation from recognized university. Age 21-30 years. Computer literacy mandatory. Selected candidates undergo 2 years training with stipend.",
    siteUrl: "https://sbi.co.in", applyUrl: "https://sbi.co.in/careers"
  },
  {
    title: "IBPS SO CRP SPL XVI Online Form 2026",
    shortTitle: "IBPS SPL XVI 2026",
    organization: "Institute of Banking Personnel Selection",
    advNumber: "CRP SPL-XVI/2026",
    category: "banking", vacancies: 896,
    startDate: "05/08/2026", lastDate: "25/08/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 25, ageMax: 35,
    qualify: "Relevant Degree (Law/IT/HR/Agriculture/etc)",
    salary: "₹36,000 - ₹63,840 (JMGS-I)",
    state: "All India",
    posts: [["IT Officer", 180], ["Agriculture Officer", 150], ["Rajbhasha Adhikari", 60], ["Law Officer", 80], ["HR/Personnel Officer", 70], ["Marketing Officer", 356]],
    elig: "IT Officer: B.E./B.Tech/MCA. Law Officer: LLB with 5 yrs enrollment. Agriculture: B.Sc Agriculture. HR: MBA HR/PGDHRM. Marketing: MBA Marketing. Age 25-35 years.",
    siteUrl: "https://ibps.in", applyUrl: "https://ibps.in/CRP-SPL-XVI"
  },
  {
    title: "IBPS RRB Officer Scale I CRP XV Online Form 2026",
    shortTitle: "IBPS RRB PO 2026",
    organization: "Institute of Banking Personnel Selection",
    advNumber: "CRP RRB-XV/OS-I/2026",
    category: "banking", vacancies: 5557,
    startDate: "08/08/2026", lastDate: "28/08/2026",
    examDate: "September 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 18, ageMax: 30,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840 (JMGS-I)",
    state: "All India", isFeatured: true,
    posts: [["Officer Scale I (PO)", 5557]],
    elig: "Bachelor's Degree from recognized university. Age 18-30 years. Proficiency in local language of the RRB applied for. Computer knowledge essential.",
    siteUrl: "https://ibps.in", applyUrl: "https://ibps.in/CRP-RRB-XV"
  },
  {
    title: "IBPS RRB Office Assistant Multipurpose CRP XV 2026",
    shortTitle: "IBPS RRB Clerk 2026",
    organization: "Institute of Banking Personnel Selection",
    advNumber: "CRP RRB-XV/OA/2026",
    category: "banking", vacancies: 4800,
    startDate: "08/08/2026", lastDate: "28/08/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 18, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 - ₹20,900 (Multipurpose Clerk)",
    state: "All India",
    posts: [["Office Assistant (Clerk)", 4800]],
    elig: "Bachelor's Degree in any discipline from recognized university. Age 18-28 years. Local language proficiency mandatory. Computer literacy required.",
    siteUrl: "https://ibps.in", applyUrl: "https://ibps.in/CRP-RRB-XV"
  },
  {
    title: "IBPS RRB Officer Scale II and III CRP XV 2026",
    shortTitle: "IBPS RRB Scale II III 2026",
    organization: "Institute of Banking Personnel Selection",
    advNumber: "CRP RRB-XV/OS-II-III/2026",
    category: "banking", vacancies: 813,
    startDate: "08/08/2026", lastDate: "28/08/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 21, ageMax: 40,
    qualify: "Graduate + Relevant Experience",
    salary: "₹48,170 - ₹62,500 (Scale II) / ₹55,200 - ₹68,340 (Scale III)",
    state: "All India",
    posts: [["Officer Scale II (GBO)", 400], ["Officer Scale II (IT)", 100], ["Officer Scale II (CA)", 50], ["Officer Scale II (Law)", 30], ["Officer Scale II (Treasury)", 20], ["Officer Scale II (Marketing)", 30], ["Officer Scale II (HR)", 23], ["Officer Scale III", 160]],
    elig: "Scale II GBO: Graduate + 1-5 yrs experience as per post. Scale III: Graduate + 5 yrs experience. IT: B.E./B.Tech. CA: CA qualification. Age 21-40 years.",
    siteUrl: "https://ibps.in", applyUrl: "https://ibps.in/CRP-RRB-XV"
  },
  {
    title: "RBI Grade B Officer DR General 2026 Online Form",
    shortTitle: "RBI Grade B 2026",
    organization: "Reserve Bank of India",
    advNumber: "RBI/GR-B/2026",
    category: "banking", vacancies: 94,
    startDate: "10/08/2026", lastDate: "10/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduation with minimum 60% marks",
    salary: "₹55,200 - ₹1,04,800 (Level 8)",
    state: "All India", isFeatured: true,
    posts: [["Grade B (DR) General", 65], ["Grade B (DR) DEPR", 15], ["Grade B (DR) DSIM", 14]],
    elig: "Graduation with min 60% marks (50% for SC/ST/PwBD). Age 21-30 years. DEPR: PG in Economics/Finance. DSIM: PG in Statistics/Mathematics/Econometrics.",
    siteUrl: "https://rbi.org.in", applyUrl: "https://rbi.org.in/careers"
  },
  {
    title: "RBI Assistant 2026 Online Form",
    shortTitle: "RBI Assistant 2026",
    organization: "Reserve Bank of India",
    advNumber: "RBI/Assistant/2026",
    category: "banking", vacancies: 450,
    startDate: "12/08/2026", lastDate: "12/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 450/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹26,170 - ₹68,800 (Level 5)",
    state: "All India", isFeatured: true,
    posts: [["Assistant (General)", 350], ["Assistant (Hindi)", 50], ["Assistant (SC/ST)", 50]],
    elig: "Bachelor's Degree in any discipline. Computer literacy. Age 20-28 years. Knowledge of local language of the Centre applied for. Typing proficiency.",
    siteUrl: "https://rbi.org.in", applyUrl: "https://rbi.org.in/careers"
  },
  {
    title: "RBI Office Attendant 2026 Online Form",
    shortTitle: "RBI Attendant 2026",
    organization: "Reserve Bank of India",
    advNumber: "RBI/Attendant/2026",
    category: "banking", vacancies: 100,
    startDate: "15/08/2026", lastDate: "15/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 450/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 18, ageMax: 26,
    qualify: "10th Pass",
    salary: "₹17,410 - ₹43,300 (Level 3)",
    state: "All India",
    posts: [["Office Attendant", 100]],
    elig: "10th Class Pass from recognized board. Age 18-26 years. Local language proficiency. No graduation required.",
    siteUrl: "https://rbi.org.in", applyUrl: "https://rbi.org.in/careers"
  },
  {
    title: "NABARD Grade A Officer 2026 Online Form",
    shortTitle: "NABARD Grade A 2026",
    organization: "National Bank for Agriculture and Rural Development",
    advNumber: "NABARD/Gr-A/2026",
    category: "banking", vacancies: 102,
    startDate: "10/08/2026", lastDate: "10/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 800/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate / PG in relevant discipline",
    salary: "₹44,500 - ₹89,150 (Level 8)",
    state: "All India", isFeatured: true,
    posts: [["RDBS (General)", 40], ["RDBS (Agriculture)", 20], ["RDBS (Economics)", 8], ["RDBS (Finance)", 10], ["RDBS (Computer/IT)", 12], ["RDBS (Legal)", 6], ["RDBS (Statistics)", 6]],
    elig: "Bachelor's/Master's degree in relevant discipline from recognized university. Age 21-30 years. Computer proficiency required.",
    siteUrl: "https://nabard.org", applyUrl: "https://nabard.org/careers"
  },
  {
    title: "NABARD Grade B Officer 2026 Online Form",
    shortTitle: "NABARD Grade B 2026",
    organization: "National Bank for Agriculture and Rural Development",
    advNumber: "NABARD/Gr-B/2026",
    category: "banking", vacancies: 25,
    startDate: "10/08/2026", lastDate: "10/09/2026",
    examDate: "November 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 800/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 25, ageMax: 32,
    qualify: "Post Graduate in relevant discipline",
    salary: "₹55,200 - ₹1,04,800 (Level 10)",
    state: "All India",
    posts: [["Grade B (DR) General", 15], ["Grade B (DR) Rajbhasha", 5], ["Grade B (DR) Protocol & Security", 5]],
    elig: "PG Degree in any discipline from recognized university with min 60% marks. Age 25-32 years. Rajbhasha: PG in Hindi with English. Security: Ex-military officers preferred.",
    siteUrl: "https://nabard.org", applyUrl: "https://nabard.org/careers"
  },
  {
    title: "SEBI Grade A Officer 2026 Online Form",
    shortTitle: "SEBI Grade A 2026",
    organization: "Securities and Exchange Board of India",
    advNumber: "SEBI/Grade-A/2026",
    category: "banking", vacancies: 97,
    startDate: "12/08/2026", lastDate: "12/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 800/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate / PG in relevant discipline",
    salary: "₹44,500 - ₹89,150 (Level 8)",
    state: "All India",
    posts: [["General", 25], ["Legal", 15], ["Information Technology", 18], ["Official Language", 4], ["Research", 10], ["Economic Research", 10], ["Statistics", 15]],
    elig: "General: Bachelor's Degree. Legal: LLB. IT: B.E./B.Tech/MCA. Economics: PG in Economics. Statistics: PG in Statistics. Age 21-30 years.",
    siteUrl: "https://sebi.gov.in", applyUrl: "https://sebi.gov.in/careers"
  },
  {
    title: "SIDBI Grade A Assistant Manager 2026",
    shortTitle: "SIDBI Grade A 2026",
    organization: "Small Industries Development Bank of India",
    advNumber: "SIDBI/Gr-A/2026",
    category: "banking", vacancies: 100,
    startDate: "08/08/2026", lastDate: "07/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 800/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate / PG in relevant field",
    salary: "₹44,500 - ₹89,150 (Level 8)",
    state: "All India",
    posts: [["Assistant Manager (General)", 70], ["Assistant Manager (Legal)", 10], ["Assistant Manager (IT)", 10], ["Assistant Manager (Hindi)", 10]],
    elig: "General: Graduate from recognized university. Legal: LLB with 2 yrs experience. IT: B.E./B.Tech. Hindi: PG in Hindi with English. Age 21-30 years.",
    siteUrl: "https://sidbi.in", applyUrl: "https://sidbi.in/careers"
  },
  {
    title: "LIC AAO Assistant Administrative Officer 2026",
    shortTitle: "LIC AAO 2026",
    organization: "Life Insurance Corporation of India",
    advNumber: "LIC/AAO/2026",
    category: "banking", vacancies: 300,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 700/-", feeSC_ST: "Rs. 80/-", feePH: "Rs. 80/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate in any discipline",
    salary: "₹53,600 - ₹1,02,090 (Level 7)",
    state: "All India", isFeatured: true,
    posts: [["AAO (Generalist)", 150], ["AAO (IT)", 40], ["AAO (Chartered Accountant)", 20], ["AAO (Actuarial)", 20], ["AAO (Rajbhasha)", 10], ["AAO (Legal)", 20], ["AAO (OTS)", 40]],
    elig: "Bachelor's Degree from recognized university. CA: ICAI qualified. IT: B.E./B.Tech. Actuarial: 5+ papers passed. Legal: LLB. Age 21-30 years.",
    siteUrl: "https://licindia.in", applyUrl: "https://licindia.in/careers"
  },
  {
    title: "LIC ADO Apprentice Development Officer 2026",
    shortTitle: "LIC ADO 2026",
    organization: "Life Insurance Corporation of India",
    advNumber: "LIC/ADO/2026",
    category: "banking", vacancies: 2000,
    startDate: "18/08/2026", lastDate: "17/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 700/-", feeSC_ST: "Rs. 80/-", feePH: "Rs. 80/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate in any discipline",
    salary: "₹35,650 - ₹67,000 (Level 6)",
    state: "All India",
    posts: [["ADO (Urban)", 800], ["ADO (Rural)", 700], ["ADO (SB)", 500]],
    elig: "Bachelor's Degree from recognized university. Age 21-30 years. Selected candidates undergo apprenticeship training before absorption.",
    siteUrl: "https://licindia.in", applyUrl: "https://licindia.in/careers"
  },
  {
    title: "SBI Circle Based Officer CBO 2026",
    shortTitle: "SBI CBO 2026",
    organization: "State Bank of India",
    advNumber: "CRPD/CBO/2026/09",
    category: "banking", vacancies: 2964,
    startDate: "01/08/2026", lastDate: "25/08/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 750/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate in any discipline + 2 yrs experience",
    salary: "₹36,000 - ₹63,840 (JMGS-I)",
    state: "All India", isFeatured: true,
    posts: [["Circle Based Officer (General)", 1480], ["Circle Based Officer (OBC)", 800], ["Circle Based Officer (SC)", 420], ["Circle Based Officer (ST)", 264]],
    elig: "Graduate from recognized university. Minimum 2 years experience in banking/financial institution. Age 21-30 years. Knowledge of local language.",
    siteUrl: "https://sbi.co.in", applyUrl: "https://sbi.co.in/careers"
  },
  {
    title: "SBI Specialist Cadre Officer SCO 2026",
    shortTitle: "SBI SCO 2026",
    organization: "State Bank of India",
    advNumber: "CRPD/SCO/2026/05",
    category: "banking", vacancies: 1040,
    startDate: "05/08/2026", lastDate: "05/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 750/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 25, ageMax: 45,
    qualify: "Relevant Degree + Experience",
    salary: "₹36,000 - ₹78,230",
    state: "All India",
    posts: [["DGM (IT)", 50], ["AGM (IT)", 80], ["Deputy Manager (System Officer)", 100], ["Manager (Credit Officer)", 150], ["Manager (Risk)", 100], ["Assistant Manager (Rajbhasha)", 60], ["Others", 500]],
    elig: "IT: B.E./B.Tech + 5-12 yrs experience. Credit: MBA Finance + 3 yrs experience. Risk: FRM/PRM preferred. Age varies by grade 25-45 years.",
    siteUrl: "https://sbi.co.in", applyUrl: "https://sbi.co.in/careers"
  },
  {
    title: "SBI Apprentice 2026 Engagement",
    shortTitle: "SBI Apprentice 2026",
    organization: "State Bank of India",
    advNumber: "CRPD/Apprentice/2026",
    category: "banking", vacancies: 6160,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice (General)", 3000], ["Apprentice (OBC)", 1500], ["Apprentice (SC)", 900], ["Apprentice (ST)", 500], ["Apprentice (EWS)", 260]],
    elig: "Graduate from recognized university. Age 20-28 years. No prior banking experience required. 1-year engagement training.",
    siteUrl: "https://sbi.co.in", applyUrl: "https://sbi.co.in/careers"
  },
  {
    title: "PNB Local Bank Officer LBO 2026",
    shortTitle: "PNB LBO 2026",
    organization: "Punjab National Bank",
    advNumber: "PNB/HR/LBO/2026",
    category: "banking", vacancies: 1025,
    startDate: "03/08/2026", lastDate: "25/08/2026",
    examDate: "September 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840 (JMGS-I)",
    state: "All India",
    posts: [["Local Bank Officer (General)", 500], ["Local Bank Officer (OBC)", 270], ["Local Bank Officer (SC)", 150], ["Local Bank Officer (ST)", 105]],
    elig: "Graduate from recognized university. Must have local language proficiency of the state. Computer literacy required. Age 20-28 years.",
    siteUrl: "https://pnbindia.in", applyUrl: "https://pnbindia.in/careers"
  },
  {
    title: "Canara Bank Apprentice 2026",
    shortTitle: "Canara Bank Apprentice 2026",
    organization: "Canara Bank",
    advNumber: "CB/Apprentice/2026",
    category: "banking", vacancies: 3000,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 3000]],
    elig: "Graduate from recognized university. Age 20-28 years. Local language of the state applied for. 1-year apprenticeship training.",
    siteUrl: "https://canarabank.com", applyUrl: "https://canarabank.com/careers"
  },
  {
    title: "Union Bank of India Local Bank Officer 2026",
    shortTitle: "UBI LBO 2026",
    organization: "Union Bank of India",
    advNumber: "UBI/LBO/2026",
    category: "banking", vacancies: 500,
    startDate: "05/08/2026", lastDate: "28/08/2026",
    examDate: "September 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840 (JMGS-I)",
    state: "All India",
    posts: [["Local Bank Officer (General)", 250], ["Local Bank Officer (OBC)", 135], ["Local Bank Officer (SC)", 75], ["Local Bank Officer (ST)", 40]],
    elig: "Graduation from recognized university. Local language proficiency. Computer literacy. Age 20-28 years.",
    siteUrl: "https://unionbankofindia.co.in", applyUrl: "https://unionbankofindia.co.in/careers"
  },
  {
    title: "Indian Bank Apprentice 2026",
    shortTitle: "Indian Bank Apprentice 2026",
    organization: "Indian Bank",
    advNumber: "IB/Apprentice/2026",
    category: "banking", vacancies: 1500,
    startDate: "12/08/2026", lastDate: "11/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 1500]],
    elig: "Graduation from recognized university. Age 20-28 years. Local language proficiency. Computer basics required.",
    siteUrl: "https://indianbank.in", applyUrl: "https://indianbank.in/careers"
  },
  {
    title: "Central Bank of India Apprentice 2026",
    shortTitle: "Central Bank Apprentice 2026",
    organization: "Central Bank of India",
    advNumber: "CBI/Apprentice/2026",
    category: "banking", vacancies: 3000,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 3000]],
    elig: "Graduate from recognized university. Age 20-28. 1-year apprenticeship training. Computer literacy.",
    siteUrl: "https://centralbankofindia.co.in", applyUrl: "https://centralbankofindia.co.in/careers"
  },
  {
    title: "Bank of Maharashtra Apprentice 2026",
    shortTitle: "BoM Apprentice 2026",
    organization: "Bank of Maharashtra",
    advNumber: "BOM/Apprentice/2026",
    category: "banking", vacancies: 600,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 600]],
    elig: "Graduation from recognized university. Age 20-28 years. 1-year engagement.",
    siteUrl: "https://bankofmaharashtra.in", applyUrl: "https://bankofmaharashtra.in/careers"
  },
  {
    title: "Bank of India Apprentice 2026",
    shortTitle: "BoI Apprentice 2026",
    organization: "Bank of India",
    advNumber: "BOI/Apprentice/2026",
    category: "banking", vacancies: 1440,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 1440]],
    elig: "Graduate from recognized university. Age 20-28. Computer proficiency.",
    siteUrl: "https://bankofindia.co.in", applyUrl: "https://bankofindia.co.in/careers"
  },
  {
    title: "Indian Overseas Bank Apprentice 2026",
    shortTitle: "IOB Apprentice 2026",
    organization: "Indian Overseas Bank",
    advNumber: "IOB/Apprentice/2026",
    category: "banking", vacancies: 550,
    startDate: "12/08/2026", lastDate: "11/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 550]],
    elig: "Graduate from recognized university. Age 20-28 years.",
    siteUrl: "https://iob.in", applyUrl: "https://iob.in/careers"
  },
  {
    title: "UCO Bank Apprentice 2026",
    shortTitle: "UCO Bank Apprentice 2026",
    organization: "UCO Bank",
    advNumber: "UCO/Apprentice/2026",
    category: "banking", vacancies: 273,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 273]],
    elig: "Graduate from recognized university. Age 20-28 years. Computer basics.",
    siteUrl: "https://ucobank.com", applyUrl: "https://ucobank.com/careers"
  },
  {
    title: "IDBI Bank Executive 2026 Online Form",
    shortTitle: "IDBI Executive 2026",
    organization: "IDBI Bank Ltd",
    advNumber: "IDBI/Executive/2026",
    category: "banking", vacancies: 1043,
    startDate: "08/08/2026", lastDate: "07/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 700/-", feeSC_ST: "Rs. 150/-", feePH: "Rs. 150/-",
    ageMin: 20, ageMax: 25,
    qualify: "Graduate in any discipline",
    salary: "₹29,000 - ₹45,000 (Contractual 1 Year)",
    state: "All India",
    posts: [["Executive (General)", 800], ["Executive (SC)", 150], ["Executive (ST)", 93]],
    elig: "Graduate from recognized university. Age 20-25 years. Computer literacy. After 1-year contract, eligible for Officer Grade on selection.",
    siteUrl: "https://idbibank.in", applyUrl: "https://idbibank.in/careers"
  },
  {
    title: "IDBI Bank Assistant Manager Grade A 2026",
    shortTitle: "IDBI AM 2026",
    organization: "IDBI Bank Ltd",
    advNumber: "IDBI/AM/2026",
    category: "banking", vacancies: 650,
    startDate: "08/08/2026", lastDate: "07/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 700/-", feeSC_ST: "Rs. 150/-", feePH: "Rs. 150/-",
    ageMin: 21, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840",
    state: "All India",
    posts: [["Assistant Manager (General)", 400], ["Assistant Manager (SC)", 100], ["Assistant Manager (OBC)", 100], ["Assistant Manager (ST)", 50]],
    elig: "Graduation from recognized university. Age 21-28 years. Computer literacy. 2 years on-the-job training.",
    siteUrl: "https://idbibank.in", applyUrl: "https://idbibank.in/careers"
  },
  {
    title: "Punjab and Sind Bank IT Officer 2026",
    shortTitle: "PSB IT Officer 2026",
    organization: "Punjab and Sind Bank",
    advNumber: "PSB/IT/2026",
    category: "banking", vacancies: 26,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 100/-",
    ageMin: 25, ageMax: 35,
    qualify: "B.E./B.Tech in IT/CS/ECE",
    salary: "₹36,000 - ₹63,840",
    state: "All India",
    posts: [["IT Officer", 26]],
    elig: "B.E./B.Tech/MCA in IT/CS/ECE from recognized university. 2 years experience in banking IT. Age 25-35 years.",
    siteUrl: "https://psbindia.com", applyUrl: "https://psbindia.com/careers"
  },
  {
    title: "Export Import Bank EXIM Bank Management Trainee 2026",
    shortTitle: "EXIM Bank MT 2026",
    organization: "Export-Import Bank of India",
    advNumber: "EXIM/MT/2026",
    category: "banking", vacancies: 30,
    startDate: "12/08/2026", lastDate: "12/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 100/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 28,
    qualify: "PG in Finance/MBA/CA",
    salary: "₹60,000 (Monthly during training)",
    state: "All India",
    posts: [["MT (Economics)", 10], ["MT (Finance)", 10], ["MT (International Business)", 5], ["MT (Legal)", 5]],
    elig: "PG/MBA in Finance/Economics/International Business from recognized university. CA/LLB for specific posts. Age 21-28 years.",
    siteUrl: "https://eximbankindia.in", applyUrl: "https://eximbankindia.in/careers"
  },
  {
    title: "India Post Payments Bank IPPB Executive 2026",
    shortTitle: "IPPB Executive 2026",
    organization: "India Post Payments Bank",
    advNumber: "IPPB/Executive/2026",
    category: "banking", vacancies: 132,
    startDate: "05/08/2026", lastDate: "28/08/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 525/-", feeSC_ST: "Rs. 150/-", feePH: "Rs. 150/-",
    ageMin: 21, ageMax: 35,
    qualify: "Graduate in any discipline",
    salary: "₹30,000 (Monthly)",
    state: "All India",
    posts: [["Executive (General)", 90], ["Executive (OBC)", 25], ["Executive (SC)", 12], ["Executive (ST)", 5]],
    elig: "Graduation from recognized university. Age 21-35 years. 1-year contract engagement. Computer literacy required.",
    siteUrl: "https://ippbonline.com", applyUrl: "https://ippbonline.com/careers"
  },
  {
    title: "Bank of Baroda Apprentice 2026",
    shortTitle: "BOB Apprentice 2026",
    organization: "Bank of Baroda",
    advNumber: "BOB/Apprentice/2026",
    category: "banking", vacancies: 4000,
    startDate: "01/08/2026", lastDate: "22/08/2026",
    examDate: "September 2026", resultDate: "November 2026",
    feeGeneral: "Rs. 300/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹15,000 (Monthly Stipend for 1 year)",
    state: "All India",
    posts: [["Apprentice", 4000]],
    elig: "Graduate from recognized university. Age 20-28 years. 1-year apprenticeship training with Bank of Baroda.",
    siteUrl: "https://bankofbaroda.in", applyUrl: "https://bankofbaroda.in/careers"
  },
  {
    title: "Karnataka Bank Probationary Officer Scale I 2026",
    shortTitle: "Karnataka Bank PO 2026",
    organization: "Karnataka Bank Ltd",
    advNumber: "KB/PO/2026",
    category: "banking", vacancies: 240,
    startDate: "10/08/2026", lastDate: "10/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 500/-", feePH: "Rs. 500/-",
    ageMin: 21, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹35,000 - ₹55,000",
    state: "All India",
    posts: [["Probationary Officer (Scale I)", 240]],
    elig: "Graduation from recognized university. Computer knowledge. Age 21-28 years. Willing to work anywhere in India.",
    siteUrl: "https://karnatakabank.com", applyUrl: "https://karnatakabank.com/careers"
  },
  {
    title: "Karur Vysya Bank Business Development Officer 2026",
    shortTitle: "KVB BDO 2026",
    organization: "Karur Vysya Bank",
    advNumber: "KVB/BDO/2026",
    category: "banking", vacancies: 500,
    startDate: "05/08/2026", lastDate: "05/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 500/-", feePH: "Rs. 500/-",
    ageMin: 21, ageMax: 30,
    qualify: "Graduate in any discipline",
    salary: "₹30,000 - ₹50,000",
    state: "All India",
    posts: [["Business Development Officer", 500]],
    elig: "Graduate from recognized university. Age 21-30 years. Computer literacy. Communication skills in English and regional language.",
    siteUrl: "https://karurvysyabank.com", applyUrl: "https://karurvysyabank.com/careers"
  },
  {
    title: "Federal Bank Probationary Officer 2026",
    shortTitle: "Federal Bank PO 2026",
    organization: "Federal Bank Ltd",
    advNumber: "FB/PO/2026",
    category: "banking", vacancies: 500,
    startDate: "08/08/2026", lastDate: "08/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 500/-", feePH: "Rs. 500/-",
    ageMin: 21, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹35,000 - ₹55,000",
    state: "All India",
    posts: [["Probationary Officer", 500]],
    elig: "Graduation from recognized university. Age 21-28 years. Computer proficiency. Willing to work across branches in India.",
    siteUrl: "https://federalbank.co.in", applyUrl: "https://federalbank.co.in/careers"
  },
  {
    title: "South Indian Bank Probationary Clerk 2026",
    shortTitle: "SIB Clerk 2026",
    organization: "South Indian Bank Ltd",
    advNumber: "SIB/Clerk/2026",
    category: "banking", vacancies: 170,
    startDate: "10/08/2026", lastDate: "10/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 500/-", feePH: "Rs. 500/-",
    ageMin: 20, ageMax: 26,
    qualify: "Graduate in any discipline",
    salary: "₹18,000 - ₹30,000",
    state: "All India",
    posts: [["Probationary Clerk", 170]],
    elig: "Graduation from recognized university. Age 20-26 years. Computer knowledge. Knowledge of regional language.",
    siteUrl: "https://southindianbank.com", applyUrl: "https://southindianbank.com/careers"
  },
  {
    title: "Tamilnad Mercantile Bank Probationary Clerk 2026",
    shortTitle: "TMB Clerk 2026",
    organization: "Tamilnad Mercantile Bank",
    advNumber: "TMB/Clerk/2026",
    category: "banking", vacancies: 130,
    startDate: "12/08/2026", lastDate: "12/09/2026",
    examDate: "October 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 500/-", feePH: "Rs. 500/-",
    ageMin: 20, ageMax: 26,
    qualify: "Graduate in any discipline",
    salary: "₹18,000 - ₹28,000",
    state: "All India",
    posts: [["Probationary Clerk", 130]],
    elig: "Graduation from recognized university. Age 20-26. Computer literacy. Tamil knowledge preferred.",
    siteUrl: "https://tnmbank.com", applyUrl: "https://tnmbank.com/careers"
  },
  {
    title: "UCO Bank Local Bank Officer LBO 2026",
    shortTitle: "UCO Bank LBO 2026",
    organization: "UCO Bank",
    advNumber: "UCO/LBO/2026",
    category: "banking", vacancies: 350,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "October 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 850/-", feeSC_ST: "Rs. 175/-", feePH: "Rs. 175/-",
    ageMin: 20, ageMax: 28,
    qualify: "Graduate in any discipline",
    salary: "₹36,000 - ₹63,840 (JMGS-I)",
    state: "All India",
    posts: [["Local Bank Officer (General)", 175], ["Local Bank Officer (OBC)", 95], ["Local Bank Officer (SC)", 50], ["Local Bank Officer (ST)", 30]],
    elig: "Graduate from recognized university. Age 20-28 years. Local language proficiency. Computer literacy required.",
    siteUrl: "https://ucobank.com", applyUrl: "https://ucobank.com/careers"
  }
];
