export default [
  {
    title: "RRB NTPC Graduate Level CEN 06/2026 Online Form",
    shortTitle: "RRB NTPC Graduate 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 06/2026",
    category: "railway", vacancies: 8113,
    startDate: "21/08/2026", lastDate: "30/09/2026",
    examDate: "December 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 36,
    qualify: "Graduate in any discipline from recognized university",
    salary: "₹19,900 - ₹63,200 (Pay Level 2-5)",
    state: "All India", isFeatured: true,
    posts: [["Station Master (SM)", 994], ["Goods Guard", 1200], ["Traffic Asst", 800], ["Sr Time Keeper", 250], ["Comml cum Ticket Clerk", 2800], ["Accounts Asst cum Typist", 1200], ["Trains Clerk", 769]],
    elig: "Bachelor's Degree from a recognized university. Computer literacy mandatory. Age: 18-36 years with usual govt relaxation for SC/ST (5 yrs), OBC (3 yrs), PH (10 yrs).",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB NTPC Undergraduate CEN 07/2026 Online Form",
    shortTitle: "RRB NTPC UG 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 07/2026",
    category: "railway", vacancies: 3445,
    startDate: "21/08/2026", lastDate: "30/09/2026",
    examDate: "January 2027", resultDate: "March 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 33,
    qualify: "12th Pass (+ NAC/NTC for some posts)",
    salary: "₹19,900 - ₹29,200 (Pay Level 2-3)",
    state: "All India", isFeatured: true,
    posts: [["Undergraduate Clerk", 1800], ["Trains Clerk", 800], ["Comml cum Ticket Clerk", 845]],
    elig: "12th Class Pass from a recognized board. Typing proficiency in English/Hindi required for some posts.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB Group D Level 1 CEN 08/2026 Online Form",
    shortTitle: "RRB Group D 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 08/2026",
    category: "railway", vacancies: 32438,
    startDate: "23/08/2026", lastDate: "22/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 36,
    qualify: "10th Pass from recognized board OR ITI from NCVT/SCVT",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India", isFeatured: true,
    posts: [["Track Maintainer Grade IV", 12000], ["Helper/Assistant", 8000], ["Assistant Lattice Man", 2500], ["Hospital Attendant", 1500], ["Sports Person/Quota", 500]],
    elig: "10th class pass from any recognized board OR ITI (in relevant trades) from institutions recognized by NCVT/SCVT. Medical fitness certificate required as per RRB medical standards.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB ALP CEN 01/2026 Online Form",
    shortTitle: "RRB ALP 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 01/2026",
    category: "railway", vacancies: 9970,
    startDate: "18/08/2026", lastDate: "18/09/2026",
    examDate: "December 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 33,
    qualify: "10th + ITI / 12th Science with Physics & Maths",
    salary: "₹19,900 - ₹63,200 (Pay Level 2-5)",
    state: "All India", isFeatured: true,
    posts: [["Assistant Loco Pilot", 9970]],
    elig: "10th pass + ITI (in relevant trades from NCVT/SCVT) OR 12th pass with Physics and Mathematics. ALP aptitude test mandatory. Age relaxation as per govt norms.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB Technician Grade I Signal CEN 02/2026 Online Form",
    shortTitle: "RRB Tech Gr I Signal 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 02/2026",
    category: "railway", vacancies: 1118,
    startDate: "18/08/2026", lastDate: "18/09/2026",
    examDate: "December 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 33,
    qualify: "Diploma / Degree in relevant engineering discipline",
    salary: "₹29,200 - ₹92,300 (Pay Level 5)",
    state: "All India",
    posts: [["Technician Grade I Signal", 600], ["Technician Grade III Telecommunication", 518]],
    elig: "Diploma/Degree in Engineering (Electrical/Electronics/Telecom/Computer Science) from a recognized institution. OR 10th + ITI with NAC/NCTC in relevant trade.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB Technician Grade III CEN 03/2026 Online Form",
    shortTitle: "RRB Tech Gr III 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 03/2026",
    category: "railway", vacancies: 8052,
    startDate: "18/08/2026", lastDate: "18/09/2026",
    examDate: "January 2027", resultDate: "April 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 33,
    qualify: "10th Pass + ITI in relevant trade",
    salary: "₹19,900 - ₹29,200 (Pay Level 2-3)",
    state: "All India",
    posts: [["Fitter", 2500], ["Welder", 800], ["Electrician", 2000], ["Mechanic", 1500], ["Painter", 400], ["Others", 852]],
    elig: "10th class pass from a recognized board with ITI (NCVT/SCVT affiliated) in relevant trade. Alternately 12th (Science) with NAC/NCTC.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB Ministerial and Isolated CEN 05/2026 Online Form",
    shortTitle: "RRB Ministerial 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. 05/2026",
    category: "railway", vacancies: 1036,
    startDate: "25/08/2026", lastDate: "25/09/2026",
    examDate: "January 2027", resultDate: "April 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 45,
    qualify: "Graduation / 12th Pass as per post",
    salary: "₹19,900 - ₹63,200",
    state: "All India",
    posts: [["Junior Stenographer (Hindi)", 120], ["Junior Stenographer (English)", 80], ["Staff Nurse", 200], ["Pharmacist", 60], ["Lab Technician", 50], ["Junior Translation Officer", 40], ["PGT/TGT Teacher", 486]],
    elig: "Varies by post: Stenographer requires shorthand speed 80 wpm Hindi/100 wpm English. Staff Nurse requires GNM/B.Sc Nursing. Teacher requires B.Ed + PG. 12th for steno with shorthand.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB Paramedical CEN 1/2026 Online Form",
    shortTitle: "RRB Paramedical 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "CEN No. RRB/01/Paramedical/2026",
    category: "railway", vacancies: 1376,
    startDate: "28/08/2026", lastDate: "27/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 36,
    qualify: "GNM / B.Sc Nursing / Diploma in relevant medical field",
    salary: "₹25,500 - ₹81,100 (Pay Level 4-5)",
    state: "All India",
    posts: [["Staff Nurse", 500], ["Pharmacist Grade II", 250], ["Lab Assistant", 150], ["Radiographer", 120], ["OT Technician", 100], ["Dresser", 80], ["ECG Technician", 50], ["Dental Hygienist", 40], ["Audiologist", 30], ["Others", 56]],
    elig: "Staff Nurse: B.Sc Nursing/GNM from recognized institute. Pharmacist: Diploma in Pharmacy. Radiographer: Diploma in Radiography. All require relevant registration where applicable.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RRB Sports Quota Group C CEN 2026 Online Form",
    shortTitle: "RRB Sports Quota 2026",
    organization: "Railway Recruitment Boards",
    advNumber: "Sports Quota CEN 2026",
    category: "railway", vacancies: 256,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 33,
    qualify: "10th/12th/Graduate + Sports Achievement",
    salary: "₹19,900 - ₹63,200",
    state: "All India",
    posts: [["Level 1 (10th Pass)", 80], ["Level 2-3 (12th Pass)", 96], ["Level 4-5 (Graduate)", 50], ["Level 6-7 (PG/Payment)", 30]],
    elig: "10th/12th/Graduation as per level applied. Represented Country in Olympics/Asian Games/Commonwealth/World Championship OR won National/State championship. Sports certificate verification mandatory.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "Indian Railway Apprentices 2026-27 (All Zones)",
    shortTitle: "Railway Zonal Apprentices 2026",
    organization: "Indian Railways (All Zones)",
    advNumber: "Various Zone-wise Notifications",
    category: "railway", vacancies: 35000,
    startDate: "10/08/2026", lastDate: "10/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "All India", isFeatured: true,
    posts: [["Northern Railway (NR)", 3093], ["Western Railway (WR)", 4183], ["Central Railway (CR)", 2422], ["Southern Railway (SR)", 3564], ["Eastern Railway (ER)", 3118], ["South Central Railway (SCR)", 4103], ["North Western Railway (NWR)", 1692], ["Others (All Zones)", 12825]],
    elig: "10th class pass (minimum 50% marks) with ITI in relevant trade from NCVT/SCVT affiliated institute. Age: 15-24 years. Medical fitness as per apprenticeship norms.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "RPF Constable and SI CEN 2026 Online Form",
    shortTitle: "RPF Constable SI 2026",
    organization: "Railway Protection Force",
    advNumber: "RPF CEN 01/2026",
    category: "railway", vacancies: 5000,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "December 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 28,
    qualify: "10th Pass (Constable) / Graduate (SI)",
    salary: "₹21,700 - ₹69,100 (Constable) / ₹35,400 - ₹1,12,400 (SI)",
    state: "All India", isFeatured: true,
    posts: [["Constable", 4548], ["Sub Inspector", 452]],
    elig: "Constable: 10th pass from recognized board, Age 18-28. SI: Graduate from recognized university, Age 18-28. Male candidates: Height 165cm+, Chest 80cm+5cm. Female: Height 157cm+. Physical measurement & PET mandatory.",
    siteUrl: "https://indianrailways.gov.in", applyUrl: "https://rrbapply.gov.in"
  },
  {
    title: "DFCCIL Executive and Junior Executive CEN 2026",
    shortTitle: "DFCCIL Executive 2026",
    organization: "Dedicated Freight Corridor Corporation of India",
    advNumber: "DFCCIL/RECT/2026",
    category: "railway", vacancies: 642,
    startDate: "05/08/2026", lastDate: "04/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 1000/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "Degree / Diploma in Engineering",
    salary: "₹25,000 - ₹68,780 (Executive) / ₹19,500 - ₹39,100 (JE)",
    state: "All India",
    posts: [["Executive (Civil)", 180], ["Executive (Electrical)", 120], ["Executive (Mechanical)", 80], ["Junior Executive (Civil)", 150], ["Junior Executive (Electrical)", 112]],
    elig: "Executive: Degree in relevant discipline from recognized university. Junior Executive: Diploma in Engineering from recognized institution. Computer knowledge mandatory.",
    siteUrl: "https://dfccil.com", applyUrl: "https://dfccil.com/careers"
  },
  {
    title: "DMRC Assistant Manager and JE Recruitment 2026",
    shortTitle: "DMRC AM JE 2026",
    organization: "Delhi Metro Rail Corporation",
    advNumber: "DMRC/HR/RECT/2026",
    category: "railway", vacancies: 482,
    startDate: "12/08/2026", lastDate: "11/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 800/-", feeSC_ST: "Rs. 300/-", feePH: "Rs. 300/-",
    ageMin: 18, ageMax: 33,
    qualify: "B.E./B.Tech / Diploma in Engineering",
    salary: "₹40,000 - ₹1,25,000 (AM) / ₹25,000 - ₹80,000 (JE)",
    state: "Delhi", isFeatured: true,
    posts: [["Assistant Manager (Civil)", 45], ["Assistant Manager (Electrical)", 42], ["Assistant Manager (S&T)", 38], ["Junior Engineer (Civil)", 120], ["Junior Engineer (Electrical)", 110], ["Junior Engineer (S&T)", 85], ["Maintainer (Civil)", 22], ["Maintainer (Electrical)", 20]],
    elig: "AM: B.E./B.Tech with minimum 60% marks from recognized university. JE: Diploma in Engineering with 3 yrs experience. Maintainer: ITI with 2 yrs experience.",
    siteUrl: "https://delhimetrorail.com", applyUrl: "https://delhimetrorail.com/careers"
  },
  {
    title: "LMRC UPMRC Various Post Recruitment 2026",
    shortTitle: "LMRC UPMRC 2026",
    organization: "Lucknow Metro Rail Corporation / UP Metro Rail Corporation",
    advNumber: "UPMRC/HR/2026",
    category: "railway", vacancies: 398,
    startDate: "08/08/2026", lastDate: "07/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 590/-", feeSC_ST: "Rs. 236/-", feePH: "Rs. 236/-",
    ageMin: 21, ageMax: 28,
    qualify: "B.E./B.Tech / Diploma / Graduate",
    salary: "₹35,000 - ₹1,12,400 (AM) / ₹25,500 - ₹81,100 (JE)",
    state: "UP", isFeatured: true,
    posts: [["Assistant Manager (Civil)", 35], ["Assistant Manager (Electrical)", 30], ["Assistant Manager (S&T)", 25], ["Station Controller/Traffic Controller", 80], ["JE (Civil)", 75], ["JE (Electrical)", 68], ["JE (S&T)", 55], ["Maintainer", 30]],
    elig: "AM: B.E./B.Tech from recognized university with 60% marks. JE: Diploma in relevant engineering. Station Controller: Graduate + Metro experience preferred.",
    siteUrl: "https://metrorailwaylucknow.org", applyUrl: "https://metrorailwaylucknow.org/careers"
  },
  {
    title: "KMRC Kolkata Metro Recruitment 2026",
    shortTitle: "KMRC Kolkata 2026",
    organization: "Kolkata Metro Rail Corporation",
    advNumber: "KMRC/HR/2026",
    category: "railway", vacancies: 180,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "December 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 21, ageMax: 30,
    qualify: "B.E./B.Tech / Diploma / Graduate",
    salary: "₹35,400 - ₹1,12,400 (Officer) / ₹19,900 - ₹63,200 (JE)",
    state: "West Bengal",
    posts: [["Station Controller", 40], ["JE (Civil)", 30], ["JE (Electrical)", 28], ["JE (S&T)", 22], ["Maintainer", 60]],
    elig: "Station Controller: Graduate with Metro operations experience. JE: Diploma/Degree in relevant engineering. Maintainer: ITI with relevant trade.",
    siteUrl: "https://metrorail.in", applyUrl: "https://metrorail.in/careers"
  },
  {
    title: "BMRC Bangalore Metro Recruitment 2026",
    shortTitle: "BMRC Bengaluru 2026",
    organization: "Bangalore Metro Rail Corporation (BMRCL)",
    advNumber: "BMRCL/HR/2026",
    category: "railway", vacancies: 280,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "December 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 300/-", feePH: "Rs. 300/-",
    ageMin: 21, ageMax: 35,
    qualify: "B.E./B.Tech / Diploma",
    salary: "₹40,000 - ₹1,20,000 (Officer) / ₹25,000 - ₹80,000 (JE)",
    state: "Karnataka",
    posts: [["Station Controller/Train Operator", 50], ["JE (Civil)", 45], ["JE (Electrical)", 40], ["JE (S&T)", 35], ["Maintainer (Civil)", 35], ["Maintainer (Electrical)", 35], ["Maintainer (S&T)", 40]],
    elig: "JE: Diploma/Degree in Engineering from AICTE recognized institute. Maintainer: ITI in relevant trade. Station Controller: Graduate with typing and computer skills.",
    siteUrl: "https://bmrc.co.in", applyUrl: "https://bmrc.co.in/careers"
  },
  {
    title: "CMRL Chennai Metro Recruitment 2026",
    shortTitle: "CMRL Chennai 2026",
    organization: "Chennai Metro Rail Corporation",
    advNumber: "CMRL/HR/2026",
    category: "railway", vacancies: 195,
    startDate: "05/08/2026", lastDate: "04/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 35,
    qualify: "B.E./B.Tech / Diploma / ITI",
    salary: "₹35,000 - ₹1,10,000 (Officer) / ₹20,000 - ₹65,000 (Maintainer)",
    state: "Tamil Nadu",
    posts: [["Station Controller", 30], ["JE (Civil)", 28], ["JE (Electrical)", 25], ["JE (S&T)", 22], ["Maintainer", 90]],
    elig: "JE: Diploma/Degree in Engineering. Maintainer: ITI (Fitter/Welder/Electrician). Station Controller: Graduate with computer proficiency. Tamil language knowledge preferred.",
    siteUrl: "https://chennaimetrorail.org", applyUrl: "https://chennaimetrorail.org/careers"
  },
  {
    title: "MMRC Mumbai Metro Phase III Recruitment 2026",
    shortTitle: "MMRC Mumbai Metro 2026",
    organization: "Mumbai Metro Rail Corporation",
    advNumber: "MMRC/HR/Phase-III/2026",
    category: "railway", vacancies: 310,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "December 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 300/-", feePH: "Rs. 300/-",
    ageMin: 21, ageMax: 35,
    qualify: "B.E./B.Tech / Diploma / Graduate",
    salary: "₹40,000 - ₹1,15,000 (Officer) / ₹25,000 - ₹75,000 (JE)",
    state: "Maharashtra",
    posts: [["Station Controller", 55], ["JE (Civil)", 50], ["JE (Electrical)", 45], ["JE (S&T)", 30], ["Maintainer", 80], ["Operation Controller", 50]],
    elig: "JE: Diploma/Degree in relevant engineering from recognized institution. Station Controller: Graduate with operational knowledge. Maintainer: ITI in relevant trade.",
    siteUrl: "https://mmrda.maharashtra.gov.in", applyUrl: "https://mmrda.maharashtra.gov.in/careers"
  },
  {
    title: "Konkan Railway Various Post CEN 2026",
    shortTitle: "Konkan Railway 2026",
    organization: "Konkan Railway Corporation Limited",
    advNumber: "KRCL/HR/RECT/2026",
    category: "railway", vacancies: 190,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 33,
    qualify: "10th/12th/Graduate/Diploma",
    salary: "₹19,900 - ₹63,200",
    state: "Maharashtra/Goa/Karnataka",
    posts: [["JE (Civil)", 35], ["JE (Electrical)", 30], ["JE (S&T)", 25], ["Section Engineer", 20], ["Technician", 40], ["Goods Guard", 20], ["Assistant Loco Pilot", 20]],
    elig: "JE: Diploma/Degree in Engineering. Technician: 10th + ITI. Section Engineer: Diploma/Degree + 3 yrs experience. Goods Guard: Graduate.",
    siteUrl: "https://konkanrailway.com", applyUrl: "https://konkanrailway.com/careers"
  },
  {
    title: "IRCON Works Engineer Recruitment 2026",
    shortTitle: "IRCON Works Engineer 2026",
    organization: "IRCON International Limited",
    advNumber: "IRCON/HR/2026",
    category: "railway", vacancies: 120,
    startDate: "12/08/2026", lastDate: "11/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 1000/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 35,
    qualify: "B.E./B.Tech in Civil/Electrical/Mechanical",
    salary: "₹30,000 - ₹1,20,000",
    state: "All India",
    posts: [["Works Engineer (Civil)", 55], ["Works Engineer (Electrical)", 40], ["Works Engineer (Mechanical)", 25]],
    elig: "B.E./B.Tech in relevant discipline from recognized university with minimum 60% marks. 1-2 yrs experience preferred. Age limit relaxable for SC/ST/OBC.",
    siteUrl: "https://ircon.org", applyUrl: "https://ircon.org/careers"
  },
  {
    title: "RVNL Site Inspector and JE Recruitment 2026",
    shortTitle: "RVNL Site Inspector 2026",
    organization: "Rail Vikas Nigam Limited",
    advNumber: "RVNL/HR/2026",
    category: "railway", vacancies: 65,
    startDate: "08/08/2026", lastDate: "07/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 1000/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 35,
    qualify: "Diploma / B.E./B.Tech in Engineering",
    salary: "₹25,000 - ₹80,000",
    state: "All India",
    posts: [["Site Inspector (Civil)", 25], ["Site Inspector (Electrical)", 20], ["JE (Civil)", 12], ["JE (Electrical)", 8]],
    elig: "Site Inspector: Diploma in Engineering + 3 yrs experience. JE: Diploma/Degree in Engineering from recognized institution.",
    siteUrl: "https://rvnl.org", applyUrl: "https://rvnl.org/careers"
  },
  {
    title: "RITES Engineer and Officer Recruitment 2026",
    shortTitle: "RITES Engineer 2026",
    organization: "RITES Limited",
    advNumber: "RITES/HR/2026",
    category: "railway", vacancies: 85,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 32,
    qualify: "B.E./B.Tech / MBA / CA",
    salary: "₹40,000 - ₹1,40,000",
    state: "All India",
    posts: [["Engineer (Civil)", 20], ["Engineer (Electrical)", 18], ["Engineer (Mechanical)", 15], ["Manager (Finance)", 12], ["Manager (HR)", 10], ["DGM (Operations)", 10]],
    elig: "B.E./B.Tech for engineering posts. MBA/CA for finance. 2-8 yrs experience depending on grade. GATE score preferred for freshers.",
    siteUrl: "https://rites.com", applyUrl: "https://rites.com/careers"
  },
  {
    title: "CRIS Assistant Software Engineer Recruitment 2026",
    shortTitle: "CRIS ASE 2026",
    organization: "Centre for Railway Information Systems",
    advNumber: "CRIS/HR/ASE/2026",
    category: "railway", vacancies: 50,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 30,
    qualify: "B.E./B.Tech / MCA in Computer Science/IT",
    salary: "₹40,000 - ₹1,25,000",
    state: "Delhi",
    posts: [["Assistant Software Engineer", 30], ["Assistant Technical Officer", 20]],
    elig: "B.E./B.Tech/MCA in CS/IT/ECE from recognized university with 60% marks. Knowledge of Java, Python, SQL, web technologies. Fresher or 1 yr experience.",
    siteUrl: "https://crisindia.com", applyUrl: "https://crisindia.com/careers"
  },
  {
    title: "RailTel Corporation Management Trainee Recruitment 2026",
    shortTitle: "RailTel MT 2026",
    organization: "RailTel Corporation of India",
    advNumber: "RailTel/HR/MT/2026",
    category: "railway", vacancies: 42,
    startDate: "10/08/2026", lastDate: "09/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 600/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 21, ageMax: 28,
    qualify: "B.E./B.Tech / MBA / MCA",
    salary: "₹40,000 - ₹1,40,000",
    state: "All India",
    posts: [["MT (Technical - Civil)", 10], ["MT (Technical - Electrical)", 8], ["MT (Technical - CSE/IT)", 12], ["MT (HR)", 5], ["MT (Finance)", 7]],
    elig: "B.E./B.Tech for technical MT. MBA (HR/Finance) for non-technical. MCA for IT. Freshers from recognized university with 60% aggregate.",
    siteUrl: "https://railtel.in", applyUrl: "https://railtel.in/careers"
  },
  {
    title: "IRCTC Tourism and Catering Recruitment 2026",
    shortTitle: "IRCTC Recruitment 2026",
    organization: "Indian Railway Catering and Tourism Corporation",
    advNumber: "IRCTC/HR/2026",
    category: "railway", vacancies: 150,
    startDate: "12/08/2026", lastDate: "11/09/2026",
    examDate: "November 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 500/-", feeSC_ST: "Rs. 250/-", feePH: "Rs. 250/-",
    ageMin: 18, ageMax: 30,
    qualify: "12th / Graduate",
    salary: "₹19,900 - ₹63,200",
    state: "All India",
    posts: [["Tourism & Travel Executive", 40], ["Catering Supervisor", 35], ["Catering Inspector", 25], ["Junior Accountant", 20], ["Publicity/Marketing Exec", 15], ["Others", 15]],
    elig: "Tourism Exec: Graduate with Diploma in Tourism preferred. Catering Supervisor: Graduate with hospitality experience. Accountant: B.Com. All posts require computer literacy.",
    siteUrl: "https://irctc.co.in", applyUrl: "https://irctc.co.in/careers"
  },
  {
    title: "Chittaranjan Locomotive Works CLW Apprentice 2026",
    shortTitle: "CLW Apprentice 2026",
    organization: "Chittaranjan Locomotive Works",
    advNumber: "CLW/Apprentice/2026",
    category: "railway", vacancies: 592,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "West Bengal",
    posts: [["Fitter", 150], ["Welder", 60], ["Electrician", 180], ["Machinist", 80], ["Painter", 40], ["Turner", 42], ["Others", 40]],
    elig: "10th pass with minimum 50% marks + ITI in relevant trade (NCVT/SCVT). Age 15-24 years. Medical fitness certificate required.",
    siteUrl: "https://clw.indianrailways.gov.in", applyUrl: "https://clw.indianrailways.gov.in/careers"
  },
  {
    title: "Banaras Locomotive Works BLW Apprentice 2026",
    shortTitle: "BLW Apprentice 2026",
    organization: "Banaras Locomotive Works",
    advNumber: "BLW/Apprentice/2026",
    category: "railway", vacancies: 374,
    startDate: "22/08/2026", lastDate: "21/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "UP",
    posts: [["Fitter", 100], ["Welder", 45], ["Electrician", 120], ["Machinist", 50], ["Others", 59]],
    elig: "10th pass with minimum 50% marks + ITI (NCVT/SCVT) in relevant trade. Age relaxation for SC/ST (5 yrs), OBC (3 yrs).",
    siteUrl: "https://blw.indianrailways.gov.in", applyUrl: "https://blw.indianrailways.gov.in/careers"
  },
  {
    title: "Integral Coach Factory ICF Chennai Apprentice 2026",
    shortTitle: "ICF Apprentice 2026",
    organization: "Integral Coach Factory, Chennai",
    advNumber: "ICF/Apprentice/2026",
    category: "railway", vacancies: 1010,
    startDate: "18/08/2026", lastDate: "17/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Tamil Nadu",
    posts: [["Fitter", 280], ["Welder", 100], ["Electrician", 320], ["Carpenter", 80], ["Painter", 60], ["Machinist", 70], ["Others", 100]],
    elig: "10th pass (50% marks) + ITI in relevant trade from NCVT/SCVT institute. Fresher ITI holders. Age 15-24 years.",
    siteUrl: "https://icf.indianrailways.gov.in", applyUrl: "https://icf.indianrailways.gov.in/careers"
  },
  {
    title: "Rail Coach Factory Kapurthala Apprentice 2026",
    shortTitle: "RCF Apprentice 2026",
    organization: "Rail Coach Factory, Kapurthala",
    advNumber: "RCF/Apprentice/2026",
    category: "railway", vacancies: 550,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Punjab",
    posts: [["Fitter", 150], ["Welder", 80], ["Electrician", 160], ["Painter", 50], ["Machinist", 55], ["Carpenter", 30], ["Others", 25]],
    elig: "10th pass with 50% marks + ITI in respective trade. NCVT/SCVT certificate mandatory. Age 15-24 years.",
    siteUrl: "https://rcf.indianrailways.gov.in", applyUrl: "https://rcf.indianrailways.gov.in/careers"
  },
  {
    title: "Rail Wheel Factory Belur Apprentice 2026",
    shortTitle: "RWF Apprentice 2026",
    organization: "Rail Wheel Factory, Belur",
    advNumber: "RWF/Apprentice/2026",
    category: "railway", vacancies: 192,
    startDate: "25/08/2026", lastDate: "24/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Karnataka",
    posts: [["Fitter", 60], ["Welder", 25], ["Electrician", 55], ["Machinist", 30], ["Turner", 22]],
    elig: "10th class pass + ITI from NCVT/SCVT recognized institute. Age 15-24 years. Medical fitness mandatory.",
    siteUrl: "https://rwf.indianrailways.gov.in", applyUrl: "https://rwf.indianrailways.gov.in/careers"
  },
  {
    title: "Rail Wheel Plant Bela Apprentice 2026",
    shortTitle: "RWP Bela Apprentice 2026",
    organization: "Rail Wheel Plant, Bela (Bihar)",
    advNumber: "RWP/Apprentice/2026",
    category: "railway", vacancies: 110,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Bihar",
    posts: [["Fitter", 35], ["Welder", 15], ["Electrician", 30], ["Machinist", 15], ["Turner", 15]],
    elig: "10th pass with ITI in respective trade from NCVT/SCVT institute. Age 15-24 years. Bihar domicile preferred.",
    siteUrl: "https://rwf.indianrailways.gov.in", applyUrl: "https://rwf.indianrailways.gov.in/careers"
  },
  {
    title: "Diesel Loco Modernisation Works DMW Patiala Apprentice 2026",
    shortTitle: "DMW Apprentice 2026",
    organization: "Diesel Loco Modernisation Works, Patiala",
    advNumber: "DMW/Apprentice/2026",
    category: "railway", vacancies: 128,
    startDate: "18/08/2026", lastDate: "17/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Punjab",
    posts: [["Fitter", 40], ["Welder", 15], ["Electrician", 38], ["Machinist", 20], ["Painter", 15]],
    elig: "10th pass + ITI in respective trade. NCVT/SCVT certificate required. Age 15-24 years.",
    siteUrl: "https://dmw.indianrailways.gov.in", applyUrl: "https://dmw.indianrailways.gov.in/careers"
  },
  {
    title: "Metro Railway Kolkata Apprentice 2026",
    shortTitle: "Metro Kolkata Apprentice 2026",
    organization: "Metro Railway, Kolkata",
    advNumber: "MRK/Apprentice/2026",
    category: "railway", vacancies: 125,
    startDate: "22/08/2026", lastDate: "21/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "West Bengal",
    posts: [["Fitter", 35], ["Electrician", 40], ["Welder", 15], ["Mechanic", 20], ["Others", 15]],
    elig: "10th pass + ITI in relevant trade from NCVT/SCVT. Age relaxation as per govt norms.",
    siteUrl: "https://metrorail.in", applyUrl: "https://metrorail.in/careers"
  },
  {
    title: "Northeast Frontier Railway NFR Apprentice 2026-27",
    shortTitle: "NFR Apprentice 2026",
    organization: "Northeast Frontier Railway",
    advNumber: "NFR/Apprentice/2026",
    category: "railway", vacancies: 5647,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "Merit Based", resultDate: "December 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Assam", isFeatured: true,
    posts: [["Fitter", 1800], ["Electrician", 1500], ["Welder", 600], ["Machinist", 350], ["Painter", 200], ["Carpenter", 200], ["Others", 997]],
    elig: "10th pass (50% marks) + ITI (NCVT/SCVT) in respective trade. Age 15-24 years. Preference to NE Region domiciles.",
    siteUrl: "https://nfr.indianrailways.gov.in", applyUrl: "https://nfr.indianrailways.gov.in/careers"
  },
  {
    title: "North Central Railway NCR Apprentice 2026",
    shortTitle: "NCR Apprentice 2026",
    organization: "North Central Railway",
    advNumber: "NCR/Apprentice/2026",
    category: "railway", vacancies: 1697,
    startDate: "18/08/2026", lastDate: "17/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "UP",
    posts: [["Fitter", 500], ["Electrician", 450], ["Welder", 200], ["Machinist", 120], ["Painter", 100], ["Others", 327]],
    elig: "10th pass + ITI from NCVT/SCVT institute. Age 15-24. NCR divisions: Prayagraj, Jhansi, Agra.",
    siteUrl: "https://ncr.indianrailways.gov.in", applyUrl: "https://ncr.indianrailways.gov.in/careers"
  },
  {
    title: "East Central Railway ECR Apprentice 2026",
    shortTitle: "ECR Apprentice 2026",
    organization: "East Central Railway",
    advNumber: "ECR/Apprentice/2026",
    category: "railway", vacancies: 1833,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Bihar",
    posts: [["Fitter", 550], ["Electrician", 480], ["Welder", 200], ["Machinist", 120], ["Others", 483]],
    elig: "10th pass with 50% marks + ITI (NCVT/SCVT). ECR HQ: Hajipur, Bihar. Divisions: Danapur, Mughalsarai, Dhanbad, Samastipur, Sonpur.",
    siteUrl: "https://ecr.indianrailways.gov.in", applyUrl: "https://ecr.indianrailways.gov.in/careers"
  },
  {
    title: "South East Central Railway SECR Apprentice 2026",
    shortTitle: "SECR Apprentice 2026",
    organization: "South East Central Railway",
    advNumber: "SECR/Apprentice/2026",
    category: "railway", vacancies: 1113,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Chhattisgarh",
    posts: [["Fitter", 350], ["Electrician", 300], ["Welder", 120], ["Painter", 80], ["Others", 263]],
    elig: "10th pass + ITI in relevant trade. SECR HQ: Bilaspur, Chhattisgarh. Divisions: Raipur, Bilaspur, Nagpur.",
    siteUrl: "https://secr.indianrailways.gov.in", applyUrl: "https://secr.indianrailways.gov.in/careers"
  },
  {
    title: "West Central Railway WCR Apprentice 2026",
    shortTitle: "WCR Apprentice 2026",
    organization: "West Central Railway",
    advNumber: "WCR/Apprentice/2026",
    category: "railway", vacancies: 722,
    startDate: "18/08/2026", lastDate: "17/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Madhya Pradesh",
    posts: [["Fitter", 220], ["Electrician", 200], ["Welder", 80], ["Machinist", 50], ["Others", 172]],
    elig: "10th pass + ITI (NCVT/SCVT). WCR HQ: Jabalpur. Divisions: Jabalpur, Bhopal, Kota.",
    siteUrl: "https://wcr.indianrailways.gov.in", applyUrl: "https://wcr.indianrailways.gov.in/careers"
  },
  {
    title: "South Western Railway SWR Apprentice 2026",
    shortTitle: "SWR Apprentice 2026",
    organization: "South Western Railway",
    advNumber: "SWR/Apprentice/2026",
    category: "railway", vacancies: 1062,
    startDate: "20/08/2026", lastDate: "19/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Karnataka",
    posts: [["Fitter", 320], ["Electrician", 280], ["Welder", 100], ["Machinist", 62], ["Painter", 50], ["Others", 250]],
    elig: "10th pass + ITI. SWR HQ: Hubli, Karnataka. Divisions: Hubli, Bangalore, Mysore.",
    siteUrl: "https://swr.indianrailways.gov.in", applyUrl: "https://swr.indianrailways.gov.in/careers"
  },
  {
    title: "South Eastern Railway SER Apprentice 2026",
    shortTitle: "SER Apprentice 2026",
    organization: "South Eastern Railway",
    advNumber: "SER/Apprentice/2026",
    category: "railway", vacancies: 1785,
    startDate: "15/08/2026", lastDate: "14/09/2026",
    examDate: "Merit Based", resultDate: "November 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "West Bengal/Jharkhand",
    posts: [["Fitter", 550], ["Electrician", 450], ["Welder", 200], ["Machinist", 120], ["Others", 465]],
    elig: "10th pass + ITI (NCVT/SCVT). SER HQ: Garden Reach, Kolkata. Divisions: Howrah, Sealdah, Adra, Chakradharpur, Kharagpur.",
    siteUrl: "https://ser.indianrailways.gov.in", applyUrl: "https://ser.indianrailways.gov.in/careers"
  },
  {
    title: "Bihar Apprentice 2026-27 Various Railway Units",
    shortTitle: "Bihar Railway Apprentice 2026",
    organization: "East Central Railway / North Eastern Railway",
    advNumber: "ER/ECR/Apprentice/2026",
    category: "railway", vacancies: 2400,
    startDate: "18/08/2026", lastDate: "17/09/2026",
    examDate: "Merit Based", resultDate: "December 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 15, ageMax: 24,
    qualify: "10th Pass + ITI",
    salary: "₹7,000 - ₹8,050 (Monthly Stipend)",
    state: "Bihar",
    posts: [["Fitter", 700], ["Electrician", 600], ["Welder", 280], ["Machinist", 150], ["Others", 670]],
    elig: "10th pass + ITI. Bihar domiciled candidates preferred. Covering Danapur, Patna, Mughalsarai, Gaya workshops.",
    siteUrl: "https://ecr.indianrailways.gov.in", applyUrl: "https://ecr.indianrailways.gov.in/careers"
  }
];
