export default [
  {
    title: "SSC CGL 2026 Online Form",
    shortTitle: "SSC CGL 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CGL/2026",
    category: "ssc", vacancies: 18274,
    startDate: "15/06/2026", lastDate: "16/07/2026",
    examDate: "September 2026", resultDate: "December 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 32,
    qualify: "Graduate in any discipline",
    salary: "₹25,500 - ₹1,42,400 (Pay Level 4-7)",
    state: "All India", isFeatured: true,
    posts: [["Income Tax Inspector", 2500], ["Central Excise Inspector", 3000], ["Auditor", 2500], ["Tax Assistant", 4000], ["Junior Statistical Officer", 500], ["Upper Division Clerk", 3000], ["Assistant Audit Officer", 1274], ["Others", 1500]],
    elig: "Bachelor's Degree from recognized university. JSO: Bachelor's degree with Statistics/Maths as subject. AAO: Bachelor's Degree with Commerce. Age 18-32 years with usual relaxation.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CHSL 2026 Online Form",
    shortTitle: "SSC CHSL 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CHSL/2026",
    category: "ssc", vacancies: 3954,
    startDate: "10/06/2026", lastDate: "10/07/2026",
    examDate: "October 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "12th Pass",
    salary: "₹19,900 - ₹63,200 (Pay Level 2-4)",
    state: "All India", isFeatured: true,
    posts: [["Lower Division Clerk (LDC)", 1500], ["Junior Secretariat Assistant (JSA)", 1000], ["Data Entry Operator (DEO)", 800], ["Data Entry Operator Grade A", 654]],
    elig: "12th Class Pass from recognized board. DEO Grade A: 12th Pass with Science and Computer. LDC/JSA: 12th Pass with typing proficiency. Age 18-27 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC MTS and Havaldar 2026 Online Form",
    shortTitle: "SSC MTS 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/MTS/2026",
    category: "ssc", vacancies: 6288,
    startDate: "20/06/2026", lastDate: "20/07/2026",
    examDate: "November 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India", isFeatured: true,
    posts: [["Multi Tasking Staff (MTS)", 4500], ["Havaldar CBIC/CBN", 1788]],
    elig: "10th Class Pass from recognized board. Age 18-27 years. Havaldar: Physical fitness and PET required for CBIC/CBN.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC GD Constable 2026 Online Form",
    shortTitle: "SSC GD 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/GD/2026",
    category: "ssc", vacancies: 39481,
    startDate: "05/11/2026", lastDate: "05/12/2026",
    examDate: "February 2027", resultDate: "June 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 23,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India", isFeatured: true,
    posts: [["CRPF Constable GD", 12000], ["BSF Constable GD", 8000], ["CISF Constable GD", 6000], ["SSB Constable GD", 5000], ["ITBP Constable GD", 3000], ["Assam Rifles Constable GD", 2481], ["NIA Constable GD", 1000], ["SSF Constable GD", 2000]],
    elig: "10th Class Pass from recognized board. Age 18-23 years. Male: Height 170cm, Chest 80+5cm. Female: Height 157cm. PET/PST mandatory.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CPO SI Delhi Police and CAPF 2026",
    shortTitle: "SSC CPO 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CPO/2026",
    category: "ssc", vacancies: 3073,
    startDate: "10/07/2026", lastDate: "10/08/2026",
    examDate: "October 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 25,
    qualify: "Graduate in any discipline",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6)",
    state: "All India",
    posts: [["Sub Inspector (Delhi Police)", 500], ["Sub Inspector (BSF)", 700], ["Sub Inspector (CRPF)", 600], ["Sub Inspector (CISF)", 400], ["Sub Inspector (ITBP)", 300], ["Sub Inspector (SSB)", 300], ["Sub Inspector (SSB-Female)", 273]],
    elig: "Bachelor's Degree from recognized university. Age 20-25 years. Physical measurement and PET/PST mandatory. Male: Height 170cm. Female: Height 157cm.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Stenographer Grade C and D 2026",
    shortTitle: "SSC Steno 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Steno/2026",
    category: "ssc", vacancies: 1590,
    startDate: "15/07/2026", lastDate: "14/08/2026",
    examDate: "November 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "12th Pass",
    salary: "₹25,500 - ₹81,100 (Grade C) / ₹19,900 - ₹63,200 (Grade D)",
    state: "All India",
    posts: [["Stenographer Grade C", 100], ["Stenographer Grade D", 1490]],
    elig: "12th Class Pass from recognized board. Shorthand proficiency: Grade C 100 wpm English/80 wpm Hindi. Grade D 80 wpm English/65 wpm Hindi. Age 18-30 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Junior Engineer JE 2026",
    shortTitle: "SSC JE 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/JE/2026",
    category: "ssc", vacancies: 1340,
    startDate: "01/07/2026", lastDate: "31/07/2026",
    examDate: "November 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 32,
    qualify: "Diploma / B.E./B.Tech in Engineering",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6-7)",
    state: "All India",
    posts: [["JE (Civil)", 600], ["JE (Electrical)", 350], ["JE (Mechanical)", 250], ["JE (Quantity Surveying)", 90], ["JE (Electronics)", 50]],
    elig: "Diploma or B.E./B.Tech in relevant engineering discipline from recognized university/institution. Age 18-32 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Selection Post Phase 14 2026",
    shortTitle: "SSC Sel Post Phase 14",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Phase-14/2026",
    category: "ssc", vacancies: 2423,
    startDate: "05/06/2026", lastDate: "05/07/2026",
    examDate: "September 2026", resultDate: "January 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "10th / 12th / Graduate (as per post)",
    salary: "₹18,000 - ₹1,12,400 (varies by post)",
    state: "All India",
    posts: [["Matriculation Level (10th)", 600], ["Higher Secondary Level (12th)", 700], ["Graduation Level", 1123]],
    elig: "10th/12th/Graduation as per post level. Various departments and ministries. Age 18-30 years with usual relaxation. Computer proficiency where required.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Selection Post Phase 15 2026",
    shortTitle: "SSC Sel Post Phase 15",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Phase-15/2026",
    category: "ssc", vacancies: 2600,
    startDate: "15/11/2026", lastDate: "15/12/2026",
    examDate: "March 2027", resultDate: "June 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "10th / 12th / Graduate (as per post)",
    salary: "₹18,000 - ₹1,12,400 (varies by post)",
    state: "All India",
    posts: [["Matriculation Level (10th)", 500], ["Higher Secondary Level (12th)", 800], ["Graduation Level", 1300]],
    elig: "10th/12th/Graduation as per level. Various central govt department posts. Age 18-30 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Junior Hindi Translator JHT 2026",
    shortTitle: "SSC JHT 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/JHT/2026",
    category: "ssc", vacancies: 437,
    startDate: "20/07/2026", lastDate: "20/08/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "Master's Degree in Hindi/English",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6)",
    state: "All India",
    posts: [["Junior Hindi Translator", 300], ["Senior Hindi Translator", 50], ["Hindi Pradhyapak", 87]],
    elig: "JHT: Master's degree in Hindi with English as compulsory subject OR Master's in English with Hindi. Hindi Pradhyapak: Master's degree with teaching experience. Age 18-30 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Scientific Assistant IMD 2026",
    shortTitle: "SSC Sci Asst IMD 2026",
    organization: "Staff Selection Commission / IMD",
    advNumber: "SSC/SciAsst/IMD/2026",
    category: "ssc", vacancies: 65,
    startDate: "15/07/2026", lastDate: "14/08/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "B.Sc with Physics/Computer Science/IT",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6)",
    state: "All India",
    posts: [["Scientific Assistant (IMD)", 65]],
    elig: "B.Sc with Physics/Computer Science/IT or B.E./B.Tech in CS/IT/ECE from recognized university. Age 18-30 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Delhi Police Constable Executive 2026",
    shortTitle: "SSC Delhi Police Constable 2026",
    organization: "Staff Selection Commission / Delhi Police",
    advNumber: "SSC/DP/Constable/2026",
    category: "ssc", vacancies: 7547,
    startDate: "01/08/2026", lastDate: "31/08/2026",
    examDate: "December 2026", resultDate: "April 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 25,
    qualify: "12th Pass",
    salary: "₹21,700 - ₹69,100 (Pay Level 3)",
    state: "Delhi",
    posts: [["Constable (Male)", 5500], ["Constable (Female)", 2047]],
    elig: "12th Class Pass from recognized board. Age 18-25 years. Male: Height 170cm, Chest 81+4cm. Female: Height 157cm. Delhi domicile preferred. Driving licence for some.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Delhi Police Head Constable Ministerial 2026",
    shortTitle: "SSC DP HC Ministerial 2026",
    organization: "Staff Selection Commission / Delhi Police",
    advNumber: "SSC/DP/HC-Min/2026",
    category: "ssc", vacancies: 735,
    startDate: "01/08/2026", lastDate: "31/08/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "12th Pass with typing",
    salary: "₹25,500 - ₹81,100 (Pay Level 4)",
    state: "Delhi",
    posts: [["Head Constable (Ministerial Male)", 500], ["Head Constable (Ministerial Female)", 235]],
    elig: "12th Pass from recognized board. English typing 30 wpm or Hindi typing 25 wpm. Age 18-27 years. Computer knowledge required.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Delhi Police AWO/TPO Head Constable 2026",
    shortTitle: "SSC DP AWO TPO 2026",
    organization: "Staff Selection Commission / Delhi Police",
    advNumber: "SSC/DP/HC-AWO/2026",
    category: "ssc", vacancies: 1225,
    startDate: "01/08/2026", lastDate: "31/08/2026",
    examDate: "November 2026", resultDate: "February 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "12th Science with Physics, Chemistry, Maths",
    salary: "₹25,500 - ₹81,100 (Pay Level 4)",
    state: "Delhi",
    posts: [["Head Constable AWO", 700], ["Head Constable TPO", 525]],
    elig: "12th Science with Physics, Chemistry and Mathematics from recognized board. Age 18-27 years. Driving licence for AWO. Physical measurement mandatory.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Delhi Police Driver Constable 2026",
    shortTitle: "SSC DP Driver 2026",
    organization: "Staff Selection Commission / Delhi Police",
    advNumber: "SSC/DP/Driver/2026",
    category: "ssc", vacancies: 1411,
    startDate: "01/08/2026", lastDate: "31/08/2026",
    examDate: "December 2026", resultDate: "April 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "10th Pass + Driving Licence",
    salary: "₹21,700 - ₹69,100 (Pay Level 3)",
    state: "Delhi",
    posts: [["Constable (Driver Male)", 1200], ["Constable (Driver Female)", 211]],
    elig: "10th Class Pass. Valid driving licence for LMV/HMV. Age 18-30 years. Driving test mandatory. Physical fitness required.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Havaldar CBIC CBN 2026 Standalone",
    shortTitle: "SSC Havaldar 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Havaldar/2026",
    category: "ssc", vacancies: 2149,
    startDate: "20/06/2026", lastDate: "20/07/2026",
    examDate: "November 2026", resultDate: "March 2027",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India",
    posts: [["Havaldar (CBIC)", 1200], ["Havaldar (CBN)", 949]],
    elig: "10th Class Pass from recognized board. Age 18-27 years. Physical Endurance and Physical Measurement Test. Height: Male 157cm, Female 152cm.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CHSL 2025 (Pending Result Cycle)",
    shortTitle: "SSC CHSL 2025",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CHSL/2025",
    category: "ssc", vacancies: 3712,
    startDate: "01/03/2025", lastDate: "01/04/2025",
    examDate: "October 2025", resultDate: "January 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "12th Pass",
    salary: "₹19,900 - ₹63,200 (Pay Level 2-4)",
    state: "All India",
    posts: [["LDC/JSA", 1500], ["DEO", 800], ["DEO Grade A", 412], ["Others", 1000]],
    elig: "12th Pass from recognized board. CHSL 2025 exam scheduled October 2025. Result expected January 2026. Candidates who appeared may track status.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC MTS 2025 Pending Recruitment",
    shortTitle: "SSC MTS 2025",
    organization: "Staff Selection Commission",
    advNumber: "SSC/MTS/2025",
    category: "ssc", vacancies: 8326,
    startDate: "01/06/2025", lastDate: "01/07/2025",
    examDate: "September 2025", resultDate: "December 2025",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India",
    posts: [["Multi Tasking Staff", 6288], ["Havaldar", 2038]],
    elig: "10th Class Pass. MTS 2025 exam completed. Result/Document Verification pending. Candidates track status on SSC website.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC GD Constable 2025 Pending Result",
    shortTitle: "SSC GD 2025 Result",
    organization: "Staff Selection Commission",
    advNumber: "SSC/GD/2025",
    category: "ssc", vacancies: 26146,
    startDate: "24/11/2024", lastDate: "31/12/2024",
    examDate: "February 2025", resultDate: "August 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 23,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India",
    posts: [["CRPF", 8000], ["BSF", 5000], ["CISF", 4000], ["SSB", 3500], ["ITBP", 2500], ["Others", 3146]],
    elig: "10th Pass. GD 2025 exam held February 2025. Final result expected August-September 2026. PET/PST ongoing for qualified candidates.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CPO 2025 Pending Result",
    shortTitle: "SSC CPO 2025",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CPO/2025",
    category: "ssc", vacancies: 4187,
    startDate: "04/06/2025", lastDate: "04/07/2025",
    examDate: "October 2025", resultDate: "February 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 25,
    qualify: "Graduate in any discipline",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6)",
    state: "All India",
    posts: [["SI (Delhi Police)", 600], ["SI (BSF)", 1000], ["SI (CRPF)", 800], ["SI (CISF)", 500], ["SI (ITBP)", 400], ["SI (SSB)", 500], ["Others", 387]],
    elig: "Graduation from recognized university. CPO 2025 exam scheduled October 2025. Physical endurance test required. Age 20-25 years.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Stenographer 2025 Pending",
    shortTitle: "SSC Steno 2025",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Steno/2025",
    category: "ssc", vacancies: 2005,
    startDate: "25/06/2025", lastDate: "25/07/2025",
    examDate: "November 2025", resultDate: "March 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "12th Pass",
    salary: "₹25,500 - ₹81,100 (Grade C) / ₹19,900 - ₹63,200 (Grade D)",
    state: "All India",
    posts: [["Steno Grade C", 150], ["Steno Grade D", 1855]],
    elig: "12th Pass. Steno 2025 exam scheduled November 2025. Shorthand skill test after written exam.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC JE 2025 Pending Result",
    shortTitle: "SSC JE 2025",
    organization: "Staff Selection Commission",
    advNumber: "SSC/JE/2025",
    category: "ssc", vacancies: 1761,
    startDate: "01/07/2025", lastDate: "31/07/2025",
    examDate: "November 2025", resultDate: "March 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 32,
    qualify: "Diploma / B.E./B.Tech in Engineering",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6-7)",
    state: "All India",
    posts: [["JE (Civil)", 800], ["JE (Electrical)", 450], ["JE (Mechanical)", 300], ["Others", 211]],
    elig: "Diploma/Degree in Engineering. JE 2025 exam held November 2025. Paper-II (Conventional) pending for qualified candidates.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Selection Post Phase 13 2026 (DV Phase)",
    shortTitle: "SSC Phase 13 DV 2026",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Phase-13/2025",
    category: "ssc", vacancies: 2423,
    startDate: "01/12/2025", lastDate: "01/01/2026",
    examDate: "March 2026", resultDate: "July 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "10th / 12th / Graduate (as per post)",
    salary: "₹18,000 - ₹1,12,400",
    state: "All India",
    posts: [["Matriculation Level", 500], ["Higher Secondary Level", 700], ["Graduation Level", 1223]],
    elig: "Phase 13 exam held March 2026. Result announced. Document Verification ongoing for qualified candidates. Post-wise allocation to various departments.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CGL 2025 (Pending Joining Phase)",
    shortTitle: "SSC CGL 2025 Status",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CGL/2025",
    category: "ssc", vacancies: 18427,
    startDate: "10/06/2025", lastDate: "10/07/2025",
    examDate: "September 2025", resultDate: "January 2026",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 32,
    qualify: "Graduate in any discipline",
    salary: "₹25,500 - ₹1,42,400 (Pay Level 4-7)",
    state: "All India",
    posts: [["Various Group B & C Posts", 18427]],
    elig: "CGL 2025 exam held September 2025. Tier-II completed. Final result and joining letters being processed. Candidates track SSC website.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CGL 2027 (Upcoming Notification)",
    shortTitle: "SSC CGL 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CGL/2027",
    category: "ssc", vacancies: 18000,
    startDate: "01/06/2027", lastDate: "01/07/2027",
    examDate: "September 2027", resultDate: "January 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 32,
    qualify: "Graduate in any discipline",
    salary: "₹25,500 - ₹1,42,400 (Pay Level 4-7)",
    state: "All India",
    posts: [["Various Group B & C Posts (Expected)", 18000]],
    elig: "Expected notification June 2027. Graduate from recognized university. Approximate vacancy figures based on previous cycles. Check SSC.gov.in for official notification.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CHSL 2027 (Upcoming Notification)",
    shortTitle: "SSC CHSL 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CHSL/2027",
    category: "ssc", vacancies: 4000,
    startDate: "01/06/2027", lastDate: "01/07/2027",
    examDate: "October 2027", resultDate: "February 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "12th Pass",
    salary: "₹19,900 - ₹63,200 (Pay Level 2-4)",
    state: "All India",
    posts: [["LDC/JSA", 1500], ["DEO", 1000], ["DEO Grade A", 500], ["Others", 1000]],
    elig: "Expected notification June 2027. 12th Pass from recognized board. Approximate vacancy figures based on previous cycles.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC GD Constable 2028 (Biennial Cycle)",
    shortTitle: "SSC GD 2028",
    organization: "Staff Selection Commission",
    advNumber: "SSC/GD/2028",
    category: "ssc", vacancies: 35000,
    startDate: "15/10/2027", lastDate: "15/11/2027",
    examDate: "February 2028", resultDate: "June 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 23,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India",
    posts: [["CRPF", 10000], ["BSF", 7000], ["CISF", 6000], ["SSB", 5000], ["ITBP", 3000], ["Others", 4000]],
    elig: "Expected notification October 2027. SSC GD is conducted biennially. 10th Pass from recognized board. Age 18-23 years. Approximate vacancy projection.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Multi Tasking Staff MTS 2027",
    shortTitle: "SSC MTS 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/MTS/2027",
    category: "ssc", vacancies: 6500,
    startDate: "01/06/2027", lastDate: "01/07/2027",
    examDate: "November 2027", resultDate: "March 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 27,
    qualify: "10th Pass",
    salary: "₹18,000 - ₹56,900 (Pay Level 1)",
    state: "All India",
    posts: [["Multi Tasking Staff", 4500], ["Havaldar", 2000]],
    elig: "Expected notification June 2027. 10th Pass. Approximate vacancies based on trend.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC CPO SI 2027 (Upcoming Cycle)",
    shortTitle: "SSC CPO 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/CPO/2027",
    category: "ssc", vacancies: 3200,
    startDate: "01/07/2027", lastDate: "01/08/2027",
    examDate: "October 2027", resultDate: "February 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 20, ageMax: 25,
    qualify: "Graduate in any discipline",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6)",
    state: "All India",
    posts: [["SI (Delhi Police)", 500], ["SI (BSF)", 800], ["SI (CRPF)", 600], ["SI (CISF)", 500], ["SI (Others)", 800]],
    elig: "Expected notification July 2027. Graduate from recognized university. Age 20-25 years. Physical measurement and PET mandatory.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Selection Post Phase 16 2027",
    shortTitle: "SSC Phase 16 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/Phase-16/2027",
    category: "ssc", vacancies: 2800,
    startDate: "01/06/2027", lastDate: "01/07/2027",
    examDate: "September 2027", resultDate: "January 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "10th / 12th / Graduate (as per post)",
    salary: "₹18,000 - ₹1,12,400",
    state: "All India",
    posts: [["Matriculation Level", 600], ["Higher Secondary Level", 800], ["Graduation Level", 1400]],
    elig: "Expected notification June 2027. Various central govt department posts. Approximate vacancy projection.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Junior Engineer JE 2027",
    shortTitle: "SSC JE 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/JE/2027",
    category: "ssc", vacancies: 1500,
    startDate: "01/07/2027", lastDate: "01/08/2027",
    examDate: "November 2027", resultDate: "March 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 32,
    qualify: "Diploma / B.E./B.Tech in Engineering",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6-7)",
    state: "All India",
    posts: [["JE (Civil)", 700], ["JE (Electrical)", 400], ["JE (Mechanical)", 250], ["Others", 150]],
    elig: "Expected notification July 2027. Diploma/Degree in relevant engineering discipline. Approximate vacancy projection.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  },
  {
    title: "SSC Junior Hindi Translator JHT 2027",
    shortTitle: "SSC JHT 2027",
    organization: "Staff Selection Commission",
    advNumber: "SSC/JHT/2027",
    category: "ssc", vacancies: 450,
    startDate: "20/07/2027", lastDate: "20/08/2027",
    examDate: "November 2027", resultDate: "February 2028",
    feeGeneral: "Rs. 100/-", feeSC_ST: "Rs. 0/-", feePH: "Rs. 0/-",
    ageMin: 18, ageMax: 30,
    qualify: "Master's Degree in Hindi/English",
    salary: "₹35,400 - ₹1,12,400 (Pay Level 6)",
    state: "All India",
    posts: [["Junior Hindi Translator", 320], ["Senior Hindi Translator", 50], ["Hindi Pradhyapak", 80]],
    elig: "Expected notification July 2027. Master's in Hindi/English with translation proficiency.",
    siteUrl: "https://ssc.gov.in", applyUrl: "https://ssc.gov.in"
  }
];
